rcS: 64mb swap now setup during install by default. Can also change to whatever you wish in installer-config.txt by adding swapsize=512M

diff --git a/scripts/etc/init.d/rcS b/scripts/etc/init.d/rcS
--- a/scripts/etc/init.d/rcS
+++ b/scripts/etc/init.d/rcS
@@ -21,6 +21,7 @@ cdebootstrap_cmdline=
 bootsize=+128M
 bootoffset=8192
 rootsize=
+swapwize=128M
 timeserver=time.nist.gov
 timezone=Etc/UTC
 locales=
@@ -749,6 +750,7 @@ echo "  boot_volume_label = $boot_volume_label"
 echo "  bootsize = $bootsize"
 echo "  bootoffset = $bootoffset"
 echo "  rootsize = $rootsize"
+echo "  swapsize = $swapsize"
 echo "  timeserver = $timeserver"
 echo "  timezone = $timezone"
 echo "  locales = $locales"
@@ -1414,6 +1416,20 @@ echo "OK"
 echo "Saving current time for fake-hwclock..."
 sync # synchronize before saving time to make it "more accurate"
 date +"%Y-%m-%d %H:%M:%S" > /rootfs/etc/fake-hwclock.data
+
+echo -n "Setting up swap..."
+if [ -n "${swapsize}" ] ; then
+    chroot /rootfs /bin/dd if=/dev/zero of=/swap bs=$swapsize count=1 >/dev/null 2>&1 || fail
+    chroot /rootfs /sbin/mkswap /swap || fail
+    chroot /rootfs /bin/chmod 600 /swap || fail
+    echo "/swap none swap sw 0 0" >> /rootfs/etc/fstab || fail
+else
+    chroot /rootfs /bin/dd if=/dev/zero of=/swap bs=64M count=1 >/dev/null 2>&1 || fail
+    chroot /rootfs /sbin/mkswap /swap >/dev/null 2>&1 || fail
+    chroot /rootfs /bin/chmod 600 /swap >/dev/null 2>&1 || fail
+    echo "/swap none swap sw 0 0" >> /rootfs/etc/fstab || fail
+fi
+echo "OK"
 
 ENDTIME=$(date +%s)
 DURATION=$((ENDTIME - REAL_STARTTIME))
